### ISSUE TITLE
Errors while running Syzscope.

### ISSUE THREAD

**Issue by neelkrish** [plummm/SyzScope#3]
I am trying to fuzz with Syzscope. But I am encountering :

Failed to get detail of a case https://syzkaller.appspot.com/bug?id=e98d2e8aa7283d11aa8e0b718d8afa1a058e6ae0
Failed to get detail of a case https://syzkaller.appspot.com/bug?id=ff42415ad0066959950f184d479c5c9e9f033e9e
Failed to get detail of a case https://syzkaller.appspot.com/bug?id=ff39495cd7e7333b7fa2c150e33e52df49ea0377
Failed to get detail of a case https://syzkaller.appspot.com/bug?id=fdcd1733bbe482196c0e15d4b42a25fe941046d0

There are a lot more. I am behind a proxy, I have set the http and https proxy path. I do see some completed test cases in the work directory.

**Comment by plummm** [comment]
I took a quick look at those 4 cases, each of them has a different reason that SyzScope may not be interested and fail to get the details.

https://syzkaller.appspot.com/bug?id=e98d2e8aa7283d11aa8e0b718d8afa1a058e6ae0 doesn't target `upstream` kernel, instead, it targets `https://git.kernel.org/pub/scm/linux/kernel/git/gregkh/usb.git usb-testing`
https://syzkaller.appspot.com/bug?id=ff42415ad0066959950f184d479c5c9e9f033e9e doesn't have any reproducers(c program or syzkaller program)
https://syzkaller.appspot.com/bug?id=ff39495cd7e7333b7fa2c150e33e52df49ea0377 targets `net-next` kernel
https://syzkaller.appspot.com/bug?id=fdcd1733bbe482196c0e15d4b42a25fe941046d0 doesn't have any reproducers.

**Comment by plummm** [comment]
Thanks for reaching out. Just to be clear, this isn't an issue on your end. Your network setup is fine as long as SyzScope managed to get some cases. You can remove the target kernel constraints here https://github.com/plummm/SyzScope/blob/71cc3dd973e7cd7bc14c2436cacc46a1a62fb942/syzscope/modules/syzbotCrawler.py#L220

In terms of no reproducers, there is no points to continue since we have no idea how to reproduce this bug.
